"""Emit pgfplots data for the complete-family contrast figure (radius 0.25).

Reads only immutable artifacts:
- artifacts/negative_paper/exp017_scientific_soundness_audit_v1.json
- artifacts/negative_paper/gate_n2_simultaneous_analysis_v1.json

Writes:
- paper/satml2027/generated/fig_family_r025.dat
- paper/satml2027/generated/fig_family_r025_axis.tex
- paper/satml2027/generated/fig_family_r025_sources.json
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
AUDIT = ROOT / "artifacts" / "negative_paper" / "exp017_scientific_soundness_audit_v1.json"
N2 = ROOT / "artifacts" / "negative_paper" / "gate_n2_simultaneous_analysis_v1.json"
OUT_DIR = ROOT / "paper" / "satml2027" / "generated"

RADIUS = 0.25
STD = "standard_cohen_certified_accuracy"
ANCH = "raw_clean_anchored_certified_accuracy"

# Fixed display order: family, then increasing step/coefficient.
ORDER = [
    ("global_mean_centering__coefficient_0.25", "Mean-centering c=0.25"),
    ("global_mean_centering__coefficient_0.5", "Mean-centering c=0.5"),
    ("global_mean_centering__coefficient_1", "Mean-centering c=1"),
    ("chowers_exact_projected_gap__coefficient_0.25", "Projected gap c=0.25"),
    ("chowers_exact_projected_gap__coefficient_0.5", "Projected gap c=0.5"),
    ("chowers_exact_projected_gap__coefficient_1", "Projected gap c=1"),
    ("gr_clip_style_two_sided__coefficient_1", "Two-sided centering c=1"),
    ("clean_boundary_active__step_0.0025", "Boundary-active 0.0025"),
    ("clean_boundary_active__step_0.005", "Boundary-active 0.005"),
    ("clean_boundary_active__step_0.01", "Boundary-active 0.01"),
    ("clean_boundary_active__step_0.02", "Boundary-active 0.02"),
    ("clean_boundary_active__step_0.04", "Boundary-active 0.04"),
    ("cohen_aligned_noisy_margin__step_0.0025", "Noisy-margin 0.0025"),
    ("cohen_aligned_noisy_margin__step_0.005", "Noisy-margin 0.005"),
    ("cohen_aligned_noisy_margin__step_0.01", "Noisy-margin 0.01"),
    ("cohen_aligned_noisy_margin__step_0.02", "Noisy-margin 0.02"),
    ("cohen_aligned_noisy_margin__step_0.04", "Noisy-margin 0.04"),
]


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main() -> None:
    audit = json.loads(AUDIT.read_text(encoding="utf-8"))
    n2 = json.loads(N2.read_text(encoding="utf-8"))
    aggregates = audit["candidate_aggregates_equal_cell_weight"]
    contrasts = {
        (c["candidate_id"], c["metric"], float(c["radius"])): c for c in n2["contrasts"]
    }
    critical = float(n2["common_critical_value"])

    rows = []
    ticks = []
    labels = []
    for index, (candidate_id, label) in enumerate(ORDER, start=1):
        agg = aggregates[candidate_id]
        std = contrasts[(candidate_id, STD, RADIUS)]
        anch = contrasts[(candidate_id, ANCH, RADIUS)]
        rows.append(
            {
                "y": index,
                "std_ca": 100.0 * float(agg["standard_certified_accuracy"][str(RADIUS)]),
                "anch_ca": 100.0 * float(agg["anchored_certified_accuracy"][str(RADIUS)]),
                "std_delta": 100.0 * float(std["point_estimate"]),
                "std_lo": 100.0 * float(std["simultaneous_lower"]),
                "std_hi": 100.0 * float(std["simultaneous_upper"]),
                "anch_delta": 100.0 * float(anch["point_estimate"]),
                "anch_lo": 100.0 * float(anch["simultaneous_lower"]),
                "anch_hi": 100.0 * float(anch["simultaneous_upper"]),
            }
        )
        ticks.append(str(index))
        labels.append(label)

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    header = (
        "y std_ca anch_ca std_delta std_lo std_hi anch_delta anch_lo anch_hi "
        "std_err anch_err"
    )
    lines = [header]
    for row in rows:
        lines.append(
            " ".join(
                [
                    str(row["y"]),
                    f"{row['std_ca']:.4f}",
                    f"{row['anch_ca']:.4f}",
                    f"{row['std_delta']:.4f}",
                    f"{row['std_lo']:.4f}",
                    f"{row['std_hi']:.4f}",
                    f"{row['anch_delta']:.4f}",
                    f"{row['anch_lo']:.4f}",
                    f"{row['anch_hi']:.4f}",
                    f"{100.0 * critical:.4f}",
                    f"{100.0 * critical:.4f}",
                ]
            )
        )
    (OUT_DIR / "fig_family_r025.dat").write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")

    axis = (
        "% Generated by scripts/generate_satml2027_figure_data.py; do not edit.\n"
        "\\pgfplotsset{familyaxis/.style={\n"
        "  ytick={" + ",".join(ticks) + "},\n"
        "  yticklabels={" + ",".join("{" + label + "}" for label in labels) + "}}}\n"
    )
    (OUT_DIR / "fig_family_r025_axis.tex").write_text(axis, encoding="utf-8", newline="\n")

    sources = {
        "generator": "scripts/generate_satml2027_figure_data.py",
        "radius": RADIUS,
        "common_critical_value_points": 100.0 * critical,
        "sources": {
            AUDIT.relative_to(ROOT).as_posix(): _sha256(AUDIT),  # forward slashes on every platform
            N2.relative_to(ROOT).as_posix(): _sha256(N2),
        },
    }
    (OUT_DIR / "fig_family_r025_sources.json").write_text(
        json.dumps(sources, indent=2) + "\n", encoding="utf-8", newline="\n"
    )
    print(OUT_DIR / "fig_family_r025.dat")


if __name__ == "__main__":
    main()
