#!/usr/bin/env python3
"""Day 1 - balance the work over both servers and emit per-GPU launch scripts.

Reads the preflight reports (measured encodes/s per GPU class and model) and the
registrations, splits every cell into item shards, assigns shards greedily to the
slowest-finishing device, and writes one shell script per GPU plus a plan JSON.

Usage:
  python day1/d1_04_plan.py --registrations configs/satml2027/exp-20260920-019a.json \
        configs/satml2027/exp-20260920-019b.json \
      --preflight results/satml2027/preflight \
      --servers A:1 B:4 --out results/satml2027/plan
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from common.devices import Device, jobs_to_json, plan_shards, summarize  # noqa: E402
from common.hashing import read_json, write_json_atomic  # noqa: E402

LAUNCH_TEMPLATE = """#!/usr/bin/env bash
# Auto-generated by d1_04_plan.py - server {server}, GPU {gpu}
# Jobs are sequential on this GPU; run one script per GPU, all in parallel.
set -euo pipefail
cd "$(dirname "$0")/../../../.."
export CUDA_VISIBLE_DEVICES={gpu}
export PYTHONUNBUFFERED=1
mkdir -p {logs}
{lines}
echo "GPU {gpu} on server {server}: all jobs finished"
"""

JOB_LINE = (
    'echo "[$(date -Is)] {cell_id} shard {shard_index}/{shard_count}"\n'
    "python satml2027/day1/d1_05_run_shard.py \\\n"
    "  --registration {registration} --cell-id {cell_id} \\\n"
    "  --shard-index {shard_index} --shard-count {shard_count} \\\n"
    "  --items {items} --banks {banks} --data-root {data_root} --out {out} \\\n"
    "  --blocks-per-forward {blocks} {extra} \\\n"
    "  2>&1 | tee -a {logs}/{cell_id}__shard{shard_index}.log"
)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--registrations", nargs="+", required=True, type=Path)
    parser.add_argument("--preflight", required=True, type=Path)
    parser.add_argument("--servers", nargs="+", required=True, help="SERVER:GPU_COUNT, e.g. A:1 B:4")
    parser.add_argument("--out", required=True, type=Path)
    parser.add_argument("--items", type=Path, default=Path("results/satml2027/items"))
    parser.add_argument("--banks", type=Path, default=Path("results/satml2027/banks"))
    parser.add_argument("--data-root", type=Path, default=Path("data"))
    parser.add_argument("--results-root", type=Path, default=Path("results/satml2027"))
    parser.add_argument("--blocks-per-forward", type=int, default=4)
    parser.add_argument("--max-shard-items", type=int, default=0)
    args = parser.parse_args()

    throughput: dict[str, dict[str, float]] = {}
    device_classes: dict[str, str] = {}
    for path in sorted(args.preflight.glob("preflight_*.json")):
        report = read_json(path)
        for gpu_class, table in report.get("throughput", {}).items():
            throughput.setdefault(gpu_class, {}).update(table)
        if report.get("devices"):
            device_classes[report["server"]] = report["devices"][0]["gpu_class"]

    devices: list[Device] = []
    for entry in args.servers:
        server, _, count = entry.partition(":")
        gpu_class = device_classes.get(server, "3090")
        devices.extend(Device(server=server, gpu_index=index, gpu_class=gpu_class) for index in range(int(count or 1)))

    cells, registration_of = [], {}
    diagnostic_ids = set()
    for path in args.registrations:
        registration = read_json(path)
        if "certification" in registration:
            draws = int(registration["certification"]["selection_draws"]) + int(registration["certification"]["confirmation_draws"])
        else:
            draws = int(registration["sampling"]["draws_per_item"])
            diagnostic_ids.add(registration["experiment_id"])
        for cell in registration["cells"]:
            cells.append(cell)
            registration_of[cell["cell_id"]] = (path, registration["experiment_id"], draws)
    jobs = plan_shards(
        cells=cells, devices=devices, throughput_table=throughput,
        draws_per_item={cell_id: value[2] for cell_id, value in registration_of.items()},
        max_shard_items=args.max_shard_items,
    )
    summary = summarize(jobs)
    summary["measured_throughput"] = throughput
    summary["devices"] = [f"{device.server}:{device.gpu_index} ({device.gpu_class})" for device in devices]
    write_json_atomic(args.out / "plan.json", {"summary": summary, "jobs": jobs_to_json(jobs)})

    scripts = args.out / "launch"
    scripts.mkdir(parents=True, exist_ok=True)
    by_device: dict[str, list] = {}
    for job in jobs:
        by_device.setdefault(job.device_key, []).append(job)
    for device_key, device_jobs in sorted(by_device.items()):
        server, gpu = device_key.split(":")
        lines = []
        for job in sorted(device_jobs, key=lambda value: -value.estimated_seconds):
            registration, experiment_id, _ = registration_of[job.cell_id]
            lines.append(
                JOB_LINE.format(
                    registration=registration.as_posix(), cell_id=job.cell_id, shard_index=job.shard_index,
                    shard_count=job.shard_count, items=args.items.as_posix(), banks=args.banks.as_posix(),
                    data_root=args.data_root.as_posix(), out=(args.results_root / experiment_id).as_posix(),
                    blocks=args.blocks_per_forward,
                    extra="--item-role development --store-features" if experiment_id in diagnostic_ids else "",
                    logs=(args.results_root / "logs").as_posix(),
                )
            )
        path = scripts / f"run_server{server}_gpu{gpu}.sh"
        path.write_text(
            LAUNCH_TEMPLATE.format(server=server, gpu=gpu, lines="\n".join(lines),
                                   logs=(args.results_root / "logs").as_posix()),
            encoding="utf-8",
        )
        path.chmod(0o755)

    print(json.dumps(summary, indent=2))
    print(f"\nlaunch scripts in {scripts}")
    for server in sorted({device.server for device in devices}):
        count = sum(1 for device in devices if device.server == server)
        print(f"  server {server}: for g in $(seq 0 {count - 1}); do nohup {scripts}/run_server{server}_gpu$g.sh & done")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
